#https://mageddo.com/tools/yaml-converter

server:
  servlet:
    encoding:
      force: 'true'
  port: '9090'
spring:
  mustache:
    servlet:
      expose-session-attributes: 'true'
    suffix: .html
  datasource:
    hikari:
      username: user01
      driver-class-name: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@127.0.0.1:1521:XE
      password: '1234 '
  servlet:
    multipart:
      maxFileSize: '20MB '
    maxRequestSize: 20MB
domain: http://127.0.0.1:9090
fileUploadPath: fileUpload

